### ISSUE TITLE
Date/Time Meta Standard

### ISSUE THREAD

**Issue by justintadlock** [justintadlock/content-type-standards#3]
I'm separating this discussion from #2 because it's likely to carry over into multiple post type standards.  The idea is that date and time should be standardized when adding a new date that's unrelated to the published date.  I propose we follow core's example of `YYYY-MM-DD hh:mm:ss` for any date fields (that's `Year-Month-Day Hour:Minute:Second`).

Plugin authors can present this to the user however they want.  What's saved in the database should be a standard date format.

Date meta keys should follow this format we have proposed for portfolio projects:
- `_project_start_date`
- `_project_end_date`

So, here's an example:
- Meta key: `_project_start_date`
- Meta value: `2014-07-29 13:41:00`
## Standard

The "Date GMT" and "GMT Offset" need only be used when they're needed.

**Date**
- Meta key: `_post_type_date`
- Meta value: `0000-00-00 00:00:00`

**Date GMT**
- Meta key: `_post_type_date_gmt`
- Meta value: `0000-00-00 00:00:00`

**GMT Offset**
- Meta key: `_post_type_gmt_offset`
- Meta value: `+-0`

**Comment by cliffordp** [comment]
*Late to the party, but still made it! ;-)

Re: https://github.com/justintadlock/content-type-standards/issues/3#issuecomment-50515383 and other "offset" discussions.... unless I'm mistaken, using a +/- *offset* is error-prone due to Daylight Savings Time.

For example, if at 3:30 PM Central Time (CDT is offset of -5 from 8:30 PM UTC) May 29, 2015, a user enters an event (or whatever) for a future date/time like 3:30 PM Central Time (C*S*T is offset of -6 from 9:30 PM UTC) November 30, 2015... wouldn't they be entering it with an offset of `-5` instead of `-6`?

Therefore, to properly compute/store times and accommodate for any unknowable future Daylight Savings Time (DST) policy changes, I believe *time zone names/strings* need to be used.

This isn't the same as storing everything in UTC time and retrieving/displaying in Central Time because the user entered it during offset -5 but the event will actually occur during offset -6.

I believe the proper way to store this (in text version) is something like `2018-11-30 3:30 PM America/Chicago`.

PHP Timezones: http://php.net/manual/en/timezones.php
- notice they're not +/- offset numbers
- notice all the State of Indiana ones: 
![screenshot 2015-05-29 15 52 51](https://cloud.githubusercontent.com/assets/1812179/7892532/dd9cac72-061a-11e5-9387-98fd8a0ad2e3.png) which is due to http://www.timeanddate.com/news/time/indiana-daylight-saving.html
- heads up about Arizona not observing DST: http://www.timeanddate.com/time/us/arizona-no-dst.html, so you can't just use "Pacific, Mountain, Central, Eastern"



Hope this feedback helps. :-)

**Comment by justintadlock** [comment]
We're just talking universal data storage here.  On output, you can account for DST or anything like that.  It shouldn't be that hard; just code.

It wouldn't hurt to take a look at what WP core is doing on the storage level.

**Comment by cliffordp** [comment]
The wp-admin General Settings page's time zone display:
![screenshot 2015-05-31 12 12 42](https://cloud.githubusercontent.com/assets/1812179/7902876/6236f068-078e-11e5-9297-905bf6257e51.png)

**Comes from https://core.trac.wordpress.org/browser/tags/4.2.2/src/wp-admin/options-general.php#L192**

`date_i18n()` function
https://core.trac.wordpress.org/browser/tags/4.2.2/src/wp-includes/functions.php#L72

`localtime()` function to determine if the time in the selected time zone is currently observing DST
http://php.net/manual/en/function.localtime.php

Time Zone is stored as a string, not an offset:
![screenshot 2015-05-31 12 08 53](https://cloud.githubusercontent.com/assets/1812179/7902878/6d895ba4-078e-11e5-8699-2aada17e8791.png)

Here's some code for comparing/converting times: http://stackoverflow.com/a/15626078/893907
```
    $triggerOn = '04/01/2013 03:08 PM';
    $user_tz = 'America/Los_Angeles';
    
    echo $triggerOn; // echoes 04/01/2013 03:08 PM
    
    $schedule_date = new DateTime($triggerOn, new DateTimeZone($user_tz) );
    $schedule_date->setTimeZone(new DateTimeZone('UTC'));
    $triggerOn =  $schedule_date->format('Y-m-d H:i:s');
    
    echo $triggerOn; // echoes 2013-04-01 22:08:00
```

Personally, I think storing FUTURE times with a UTC Offset isn't the right way to do it.
You could get away with storing PAST times as UTC Offsets because you know what the offset was at that time.
But you never really know what the offset WILL BE (your app will have to determine what the offset will be on that future date, with the assumption that laws won't change).
If you do [+/- calculations to convert all times to UTC](http://en.wikipedia.org/wiki/Time_zone#Time_zone_conversions) before comparing, I don't think it holds up when entering FUTURE dates/times.


*Whether or not my opinion is agreed is ok. I just wanted to share. :)
